name: build komodo (add test later:))

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
      -
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      -
        run: cd ./ui/komodo && npm install && npm run build
      -
        name: Build all assets by crosscompiling them
        run: ./scripts/ci/release.sh
      -
        name: Make target binarys executable
        run: "chmod -R 777 ./bin"
      -
        name: capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: |
              ./bin/linux/amd64
              ./bin/darwin/amd64
              ./bin/darwin/arm64
