on: push
name: crosscompile komodo binarys
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
      -
        name: Build all assets by crosscompiling them
        run: ./scripts/ci/release.sh
      -
        name: capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: ./bin/
      -
